version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    ports:
        - 80:80
        - 443:443
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:443;http://+:80
        - ASPNETCORE_Kestrel__Certificates__Default__Password=trustymctrusty
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        - USER_SECRETS_ID=8cf3794d-fb4b-4331-a137-fbeea0623a67
    volumes:
        - ~/.aspnet/https:/https:ro
        - $APPDATA/Microsoft/UserSecrets/$USER_SECRETS_ID:/root/.microsoft/usersecrets/$USER_SECRETS_ID
    build:
      context: .
      dockerfile: Api/Dockerfile
