# fly.toml app configuration file generated for downtown-app on 2023-12-06T20:27:32-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "downtown-app"
primary_region = "yul"

[build]
  image = "meatyharvey/downtown-app-prod:latest"

[env]
  ASPNETCORE_URLS = "http://+:8080"
  Accounts__Auth0__Audience = "https://downtownapp/api"
  Accounts__Auth0__Authority = "https://downtown-app.us.auth0.com/"
  Cloudinary__ApiKey = "277262858688816"
  Cloudinary__Cloudname = "dwixnc66t"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
